### ISSUE TITLE
Repeated calculation

### ISSUE THREAD

**Issue by BenfenYU** [chauncygu/Multi-Agent-Constrained-Policy-Optimisation#1]
It seems that the commutative variable is recalculated here：

First time:
https://github.com/chauncygu/Multi-Agent-Constrained-Policy-Optimisation/blob/2f3e516c0d58e67515b7b5718ec11685ea0556cb/MACPO/macpo/algorithms/r_mappo/r_macpo.py#L403

Repeated :
https://github.com/chauncygu/Multi-Agent-Constrained-Policy-Optimisation/blob/2f3e516c0d58e67515b7b5718ec11685ea0556cb/MACPO/macpo/algorithms/r_mappo/r_macpo.py#L426

**Comment by chauncygu** [comment]
Hi, Benfen, Thanks for comments, We will clean the code again.
