### ISSUE TITLE
Mismatch between code and paper

### ISSUE THREAD

**Issue by BenfenYU** [chauncygu/Multi-Agent-Constrained-Policy-Optimisation#2]
Hi, thanks for your excellent job. I find a mismatch between code and paper about V-value network. As follows,
In paper:
<img width="891" alt="image" src="https://user-images.githubusercontent.com/33017944/166640370-b0bb3a0d-4582-4be6-8afa-a0bd80f414a5.png">

In code:
![image](https://user-images.githubusercontent.com/33017944/166640450-11d4bdc5-73a4-4f1c-b3aa-a5840c981ecc.png)

Will different ways of using V-value network have a great impact on the experimental results? Thank you!

**Comment by chauncygu** [comment]
Hi, Thanks for comments, we have revised the algorithm, it should be global, by using concate()
