### ISSUE TITLE
Render

### ISSUE THREAD

**Issue by BenfenYU** [chauncygu/Multi-Agent-Constrained-Policy-Optimisation#3]
Hello, can you release your render code?
I use the render function of baseclass of AntEnv, however I got this:
![image](https://user-images.githubusercontent.com/33017944/167050032-63e017b5-8ac4-44aa-b302-b97156569fd2.png)
![image](https://user-images.githubusercontent.com/33017944/167050064-ab387fcb-2747-48dc-bb79-fc9dfd2a9f9e.png)

**Comment by chauncygu** [comment]
Hi, Thanks for your comments, please use the command in your environments, "env.render()"
