### ISSUE TITLE
grad norm explosion!

### ISSUE THREAD

**Issue by mhmd97z** [chauncygu/Multi-Agent-Constrained-Policy-Optimisation#5]
I noticed that when the critic learning rate in my application is rather large (lr=0.008 and critic_lr=0.5), the grad norm goes to infinity, and values turn to Nan.
Clipping grad norm is suggested in such a scenario, but first I wanted to know your opinion on this matter. Is such critic_lr way off its meaningful range of values and I should not explore it, or I should go with clipping grad norm?!
Thanks!

**Comment by chauncygu** [comment]
Hi, Thanks for your comments, I think you can try to clip it.
