### ISSUE TITLE
_use_naive_recurrent_generator

### ISSUE THREAD

**Issue by SatriaChen** [chauncygu/Multi-Agent-Constrained-Policy-Optimisation#6]
I try to use to naive_recurrent train the model, but when using the macpo algorithm, naive_recurrent_generator provides 17 values, but the 18 values required to update the sample of the network in the training class, maybe do not include the "aver_ episode_ costs"。

What's the matter and how can I modify it.
Thanks!

**Comment by chauncygu** [comment]
Hi, thanks for your message, the code can work based on our network, if you want to use another network or policy to train, and develop a new method based on our method, maybe you can email me, and tell me what you want to do in detail.
